name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install-build-test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.18
        uses: actions/setup-node@v2
        with:
          node-version: 16.18

      - name: Install Dependencies
        run: yarn

      - name: Build & Test
        run: yarn turbo run build test lint
